import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { AuthProvider } from "./components/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Mobile Shop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <Toaster position="top-right" reverseOrder={true} />
        <div className="container mx-auto">
          <AuthProvider>{children}</AuthProvider>
        </div>
   
      </body>
    </html>
  );
}
